if: tag IS blank
fail_fast: true
sudo: required
services:
- docker
env:
  global:
  - REGISTRY_USER=slashe
  - secure: aLBrkjxS4hIILKiWkFWoLVt0f0t5q+sE0GkP7wSnKJgPHW7aH9pi46Uuh0s82EOrU27uJW3ObtXqYg+WwE3EVsd71IcWI5+w4G81H/ZQ8SR4NcRmgJIA0dNAwqPli541LmfBDtrmcz8JZqPUSr//y5qHCMl2Jqmp1gaZ92mOdVhgWeW/aAlWxA7dMmqkZGbStaA5tzA0r5RsI3tvcpjvw6PdAp3vVgYVn7GLwRpiz3W1FaOjyKSpchrKWOVafh6vx9e++iZatNJGzS6Uzy559ze/Fnz/xqbRjiuSdTz/u01y6sAMBTjXWzpcnsnvr+pda6tcAoWWFZATT78R/j1N8ttjejpO1pftnFhlOOnEz6qPMaYpiN2dJCtpny6/lWxysQPzBGaB+y/aM0oYejIdTnjAX+Ar75zSpF/opTmZMh0jlyY3LG9dB5XT/ru5aynDxLCsA2rVVMIM/d4Gz0mpxEWyhpgi+8GFJo+vHOs7oA90BetSjWT9GlhVy383YSBYlB/ATRshoGSGlxNfzXyZPZ0cTxXJrdpatNpYzLnKgDE1Nsaj2Iw19FE8lfNqgUWZHzxLPidVDaxibX/Ph0IYJ/jfpDrsLwqPU7SDZpFA4wIGHBRRN9UOXsRIHHpry3SOJkVUz9Qy6BGD6PA/jMYbEAHOs8RPUJNq9Tdr4FuB3OU=
  - secure: oyL0/JkcWnGdIbESma1RRUwEx6FHRHHsyiZcFZXOydXpYKZWX4V+KKyNcJAfZ6CRATajs/yRmNAqtQLgBGRAecrL/DkfhmiJhpWc/w4tIgaueTnB9jB/GP05fwcmWTYYPzV2TBZFxoEKvMM/gRkuGnc/0h0OJU+x1QM9kFrfNFwVQ2orLAstZNU5DdfEALvMHFG0mVOXOBv6SBlTttbcTmLXCZK/rdJ0OVrxak47ltsTiT6d9FgroZFlhxUiJVxtvvL6G98A3zCzEbStlayHHb6djElUZpKrR0CcezMOlTsUQ6Msq/K2TxFe4foWKnpbOEeguJEq05wqUgM/5+qyRCA1xx1lMQblfK4k1gNYvrhOe+6lhRek1n060Iwxz0kRja6PEIb08kgnlU6SNpwrQGdnw6Ek14a8Y0tVomad7hdP/ne83SwSA32hOa7XrZApA9XLy7wq13op+ZGbU9SQeBLFSvArGyXG+WBbKEk063Rv47zlFoySSyx8e2UnfxhnXdV0EALCvAnihc5InabOfmamcl62v516pJ5aNN/bA4JeS2IbqxSCWfxP1nguwu0G52c/c4d8EmajUOLP3hRJxnPc7a9LEWOqxzhDYGrj4fIUuQvj3eqm8j7vrVCW8Yvmkie9+HGxdjpBxF7Mr+NUY3v/Hg2rBPXb+YHBOGLS0Lc=
script:
- git checkout master
- version=$(npm version patch)
- docker build --tag $REGISTRY_USER/docker-node:$version .
after_script:
- docker images
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
- docker push $REGISTRY_USER/docker-node:$version
after_success:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- git add .
- git tag $version -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER [skip
  ci]"
- git commit --amend -m "TravisCI build $version [skip ci]"
- git push --repo=https://$GITHUB_PERSONAL_ACCESS_TOKEN_FOR_TRAVIS@github.com/m-slashe/docker-node.git
  --all
- git push --repo=https://$GITHUB_PERSONAL_ACCESS_TOKEN_FOR_TRAVIS@github.com/m-slashe/docker-node.git
  --tags